# Basic If-Else Statements:

In [3]:
# 1. Write a Python program to check if a given number is positive or negative.

num = float(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

Enter a number:  -5


Negative number


In [7]:
# 2. Create a program that determines if a person is eligible to vote based on their age.

age = int(input("Enter the Age"))
if age >= 18:
    print("is eligible")
else:
    print("not eligible")

Enter the Age 18


is eligible


In [13]:
# 3. Develop a program to find the maximum of two numbers using if-else statements.

def maximum(a, b):
     
    if a >= b:
        return a
    else:
        return b
     
# Driver code
a = 2
b = 4
print(maximum(a, b))

4


In [27]:
# 4. Write a Python script to classify a given year as a leap year or not.

def check_leap_year(year):
    """
    Check if the given year is a leap year or not.
    """
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                print(f"{year} is a leap year")
            else:
                print(f"{year} is not a leap year")
        else:
            print(f"{year} is a leap year")
    else:
        print(f"{year} is not a leap year")


check_leap_year(2023)



2023 is not a leap year


In [28]:
# 5. Create a program that checks whether a character is a vowel or a consonant.

def vowelOrConsonant(x): 
  
    if (x == 'a' or x == 'e' or
        x == 'i' or x == 'o' or x == 'u'): 
        print("Vowel") 
    else: 
        print("Consonant") 
vowelOrConsonant('c') 
vowelOrConsonant('e')

Consonant
Vowel


In [33]:
# 6. Implement a program to determine whether a given number is even or odd.

num = int (input ("Enter any number to test whether it is odd or even: "))

if (num % 2) == 0:

              print ("The number is even")

else:

              print ("The provided number is odd")

Enter any number to test whether it is odd or even:  6


The number is even


In [34]:
# 7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

num_1 = 4
num_2 = -6
num_3 = 0
num_4 = -875
# calculating absolute values of input integers
print("absolute value of 4 = ", abs(num_1))
print("absolute value of -6 = ", abs(num_2))
print("absolute value of 0 = ", abs(num_3))
print("absolute value of -875 = ", abs(num_4))

absolute value of 4 =  4
absolute value of -6 =  6
absolute value of 0 =  0
absolute value of -875 =  875


In [35]:
# 8. Develop a program that determines the largest of three given numbers using if-else statements.

num1 = 10
num2 = 14
num3 = 12

if (num1 >= num2) and (num1 >= num3):
   largest = num1
elif (num2 >= num1) and (num2 >= num3):
   largest = num2
else:
   largest = num3

print("The largest number is", largest)

The largest number is 14


In [36]:
# 9. Create a program that checks if a given string is a palindrome.

def isPalindrome(s):
    return s == s[::-1]
 
 
# Driver code
s = "madam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


In [ ]:
# 10. Write a Python program to calculate the grade based on a student's score.

print("Enter Marks Obtained in 5 Subjects: ")
markOne = int(input())
markTwo = int(input())
markThree = int(input())
markFour = int(input())
markFive = int(input())

tot = markOne+markTwo+markThree+markFour+markFive
avg = tot/5

if avg>=91 and avg<=100:
    print("Your Grade is A1")
elif avg>=81 and avg<91:
    print("Your Grade is A2")
elif avg>=71 and avg<81:
    print("Your Grade is B1")
elif avg>=61 and avg<71:
    print("Your Grade is B2")
elif avg>=51 and avg<61:
    print("Your Grade is C1")
elif avg>=41 and avg<51:
    print("Your Grade is C2")
elif avg>=33 and avg<41:
    print("Your Grade is D")
elif avg>=21 and avg<33:
    print("Your Grade is E1")
elif avg>=0 and avg<21:
    print("Your Grade is E2")
else:
    print("Invalid Input!")

Enter Marks Obtained in 5 Subjects: 


 100
 90
 80
 70
 60


Your Grade is B1


# Nested If-Else Statements:

In [38]:
# 11. Write a program to find the largest among three numbers using nested if-else statements.

# input three integer numbers 
a=int(input("Enter A: "))
b=int(input("Enter B: "))
c=int(input("Enter C: "))

# conditions to find largest 
if a>b:
    if a>c:
        g=a
    else:
        g=c
else:
    if b>c:
        g=b
    else:
        g=c

# print the largest number 
print("Greater  = ",g)

Enter A:  10
Enter B:  20
Enter C:  50


Greater  =  50


In [40]:
# 12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

# Function to check if the triangle
# is equilateral or isosceles or scalene
def checkTriangle(x, y, z):
 
    # _Check for equilateral triangle
    if x == y == z:
        print("Equilateral Triangle")
 
    # Check for isosceles triangle
    elif x == y or y == z or z == x:
        print("Isosceles Triangle")
 
    # Otherwise scalene triangle
    else:
        print("Scalene Triangle")
 
 
# Driver Code
 
# Given sides of triangle
x = 8
y = 7
z = 9
 
# Function Call
checkTriangle(x, y, z)

Scalene Triangle


In [42]:
# 13. Develop a program that checks if a year is a leap year and also if it is a century year.

# Python program to check if year is a leap year or not

year = 2023

# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

2023 is not a leap year


In [43]:
# 14. Write a Python script to determine if a number is positive, negative, or zero.

num = float(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

Enter a number:  0


Zero


In [55]:
# 15. Create a program to check if a person is a teenager (between 13 and 19 years old).

age = int(input('Please enter a persons age.'))
if age >= 13: 
    print('The person is an Teenager.')
else:
    age <= 19
    print('The person is not an Teenager.')


Please enter a persons age. 10


The person is not an Teenager.


In [56]:
# 16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

def findTriangle(a, n) : 
      
    b = [] 
    # Finding the square of each element of array 
    for i in range(n) : 
        b.append(a[i] * a[i]) 
      
    # Sort the sides of array and their squares.  
    a.sort() 
    b.sort()  
     
    # x for acute triangles 
    # y for right triangles 
    # z for obtuse triangles 
    x, y, z = 0, 0, 0
      
    for i in range(n) : 
        p = i+1
        q = i+1
        for j in range(i + 1, n) : 
            # Finding the farthest point p where 
            # a^2 + b^2 >= c^2. 
            while (p<n-1 and b[i]+b[j]>=b[p+1]) : 
                p += 1
            q = max(q, p) 
            # Finding the farthest point q where  
            # a + b > c. 
            while (q<n-1 and a[i]+a[j]>a[q+1]) : 
                q += 1
                  
            # If point p make right triangle. 
            if (b[i]+b[j]==b[p]) : 
                # All triangle between j and p are acute 
                # triangles. So add p - j - 1 in x. 
                x += max(p - j - 1, 0) 
                # Increment y by 1. 
                y += 1 
                # All triangle between q and p are acute 
                # triangles. So add q - p in z. 
                z += q - p 
            # If no right triangle 
            else : 
                # All triangle between j and p are acute 
                # triangles. So add p - j in x. 
                x += max(p - j, 0) 
                # All triangle between q and p are acute  
                # triangles. So add q - p in z. 
                z += q - p 
      
    print("Acute Triangle:",x ) 
    print("Right Triangle:", y)  
    print("Obtuse Triangle:", z)  
  
  
# Driver Code  
if __name__ == "__main__" : 
  
    arr = [2, 3, 9, 10, 12, 15] 
    n = len(arr) 
    findTriangle(arr, n)

Acute Triangle: 2
Right Triangle: 1
Obtuse Triangle: 4


In [57]:
# 17. Write a Python program to calculate the roots of a quadratic equation.

import cmath

a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-3+0j) and (-2+0j)


In [58]:
# 18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
#for Tuesday, etc.).

import datetime
import calendar
 
def findDay(date):
    born = datetime.datetime.strptime(date, '%d %m %Y').weekday()
    return (calendar.day_name[born])
 
# Driver program
date = '03 02 2019'
print(findDay(date))

Sunday


In [62]:
# 19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

2023 is not a leap year


In [63]:
# 20. Develop a program that checks if a given number is prime or not using nested if-else statements.

from math import sqrt

# Number to be checked for prime
n = 9

flag = 0

if(n > 1):
	for k in range(2, int(sqrt(n)) + 1):
		if (n % k == 0):
			flag = 1
		break
	if (flag == 0):
		print(n," is a Prime Number!")
	else:
		print(n," is Not a Prime Number!")
else:
	print(n," is Not a Prime Number!")

9  is a Prime Number!


# Elif Statements:

In [86]:
# 21. Write a Python program to assign grades based on different ranges of scores using elif statements.

markOne = int(input())
markTwo = int(input())
markThree = int(input())
markFour = int(input())
markFive = int(input())

tot = markOne+markTwo+markThree+markFour+markFive
avg = tot/5

if avg>=91 and avg<=100:
    print("Your Grade is A1")
elif avg>=81 and avg<91:
    print("Your Grade is A2")
elif avg>=71 and avg<81:
    print("Your Grade is B1")
elif avg>=61 and avg<71:
    print("Your Grade is B2")
elif avg>=51 and avg<61:
    print("Your Grade is C1")
elif avg>=41 and avg<51:
    print("Your Grade is C2")
elif avg>=33 and avg<41:
    print("Your Grade is D")
elif avg>=21 and avg<33:
    print("Your Grade is E1")
elif avg>=0 and avg<21:
    print("Your Grade is E2")
else:
    print("Invalid Input!")

 20
 60
 70
 40
 60


Your Grade is C2


In [87]:
# 23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
#elif statements.

def BMI(height, weight): 
    bmi = weight/(height**2) 
    return bmi 
  
# Driver code 
height = 1.79832
weight = 70
  
# calling the BMI function 
bmi = BMI(height, weight) 
print("The BMI is", format(bmi), "so ", end='') 
  
# Conditions to find out BMI category 
if (bmi < 18.5): 
    print("underweight") 
  
elif ( bmi >= 18.5 and bmi < 24.9): 
    print("Healthy") 
  
elif ( bmi >= 24.9 and bmi < 30): 
    print("overweight") 
  
elif ( bmi >=30): 
    print("Suffering from Obesity") 

The BMI is 21.64532402096181 so Healthy


In [92]:
# 24. Create a program that determines whether a given number is positive, negative, or zero using elif
#statements.

num = int(input("Input a number: "))

# Check if the number is greater than zero.
if num > 0:
   # If true, print that it is a positive number.
   print("It is a positive number")
# Check if the number is equal to zero.
elif num == 0:
   # If true, print that it is zero.
   print("It is zero")
else:
   # If the above conditions are not met, print that it is a negative number.
   print("It is a negative number")

Input a number:  -2


It is a negative number


In [93]:
# 25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
#statements.

character = input("Enter a character: ")

lowerLetters = "abcdefghijklmnopqrstuvwxyz"
upperLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
digits = "0123456789"
lowerCount = 0
upperCount = 0
digitCount = 0
nonAlphaCount = 0

for ch in character:
    for ch in lowerLetters:
        lowerCount += 1
    for ch in upperLetters:
        upperCount += 1
    for ch in digits:
        digitCount += 1
    else:
        nonAlphaCount += 1

if lowerCount > 0:
    print(character, "is a lower case letter.")
elif upperCount > 0:
    print(character, "is an upper case letter.")
elif digitCount > 0:
    print(character, "is a digit.")
elif nonAlphaCount > 0:
    print(character, "is a non-alphanumeric character.")

Enter a character:  Upper


Upper is a lower case letter.


In [94]:
# 26. Implement a program to calculate the discounted price based on different purchase amounts using elif
#statements.

p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  5000


Discount Amount = 0.00
Net Bill Amount = 5000.00


In [95]:
# 27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
#statements.

# Function to calculate the 
# electricity bill 
def calculateBill(units):
 
    # Condition to find the charges 
    # bar in which the units consumed 
    # is fall 
    if (units <= 100):
      
        return units * 10; 
     
    elif (units <= 200):
     
        return ((100 * 10) +
                (units - 100) * 15); 
     
    elif (units <= 300):
      
        return ((100 * 10) +
                (100 * 15) +
                (units - 200) * 20); 
     
    elif (units > 300):
     
        return ((100 * 10) +
                (100 * 15) +
                (100 * 20) +
                (units - 300) * 25); 
     
    return 0; 
 

units = 250; 
print(calculateBill(units)); 

3500


In [97]:
# 28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
#statements.

def Valid(a, b, c, d):
 
    # Check condition
    if (a + b + c + d == 360):
        return True;
     
    return False;
 
 

a = 80; b = 70; c = 100; d = 110;
 
if (Valid(a, b, c, d)):
    print("Valid quadrilateral");
else:
    print("Invalid quadrilateral");

Valid quadrilateral


In [98]:
# 29. Write a Python script to determine the season based on a user-provided month using elif statements.

month = input("Input the month (e.g. January, February etc.): ")
day = int(input("Input the day: "))

if month in ('January', 'February', 'March'):
	season = 'winter'
elif month in ('April', 'May', 'June'):
	season = 'spring'
elif month in ('July', 'August', 'September'):
	season = 'summer'
else:
	season = 'autumn'

if (month == 'March') and (day > 19):
	season = 'spring'
elif (month == 'June') and (day > 20):
	season = 'summer'
elif (month == 'September') and (day > 21):
	season = 'autumn'
elif (month == 'December') and (day > 20):
	season = 'winter'

print("Season is",season)

Input the month (e.g. January, February etc.):  April
Input the day:  5


Season is spring


In [99]:
# 30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
#elif statements.

if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

2023 is not a leap year


# Basic Level:

In [2]:
# 1. Write a Python program that checks if a given number is positive, negative, or zero.

num = float(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

Enter a number:  5


Positive number


In [3]:
# 2. Create a program to determine if a person is eligible to vote based on their age.

age = int(input("Enter age : "))

if age >= 18:
    print("Eligible for Voting!")
else:
    print("Not Eligible for Voting!")

Enter age :  18


Eligible for Voting!


In [4]:
# 3. Write a program to find the maximum of two given numbers using conditional statements

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# printing the maximum value
if(num1 > num2):
  print(num1, "is greater")
elif(num1 < num2):
    print(num2, "is greater")
else:
    print("Both are equal")

Enter the first number:  5
Enter the second number:  2


5 is greater


In [5]:
# 4. Develop a program that calculates the grade of a student based on their exam score.

print("Enter Marks Obtained in 5 Subjects: ")
markOne = int(input())
markTwo = int(input())
markThree = int(input())
markFour = int(input())
markFive = int(input())

tot = markOne+markTwo+markThree+markFour+markFive
avg = tot/5

if avg>=91 and avg<=100:
    print("Your Grade is A1")
elif avg>=81 and avg<91:
    print("Your Grade is A2")
elif avg>=71 and avg<81:
    print("Your Grade is B1")
elif avg>=61 and avg<71:
    print("Your Grade is B2")
elif avg>=51 and avg<61:
    print("Your Grade is C1")
elif avg>=41 and avg<51:
    print("Your Grade is C2")
elif avg>=33 and avg<41:
    print("Your Grade is D")
elif avg>=21 and avg<33:
    print("Your Grade is E1")
elif avg>=0 and avg<21:
    print("Your Grade is E2")
else:
    print("Invalid Input!")

Enter Marks Obtained in 5 Subjects: 


 10
 50
 40
 90
 60


Your Grade is C2


In [7]:
# 5. Create a program that checks if a year is a leap year or not.

year = int(input("Enter year"))

if (year%400 == 0) or (year%4==0 and year%100!=0):
    print("Leap Year")
else:
    print("Not a Leap Year")

Enter year 2023


Not a Leap Year


In [8]:
# 6. Write a program to classify a triangle based on its sides' lengths.

def checkTypeOfTriangle(a,b,c):
    sqa = pow(a, 2)
    sqb = pow(b, 2)
    sqc = pow(c, 2)
 
    if (sqa == sqc + sqb or
        sqb == sqa + sqc or
        sqc == sqa + sqb):
        print("Right-angled Triangle")
 
    elif(sqa > sqc + sqb or
            sqb > sqa + sqc or
            sqc > sqa + sqb):
        print("Obtuse-angled Triangle")
 
    else:
        print("Acute-angled Triangle")
 

if __name__ == '__main__':
    a = 2
    b = 2
    c = 2
 
    # Function Call
    checkTypeOfTriangle(a, b, c)

Acute-angled Triangle


In [9]:
# 7. Build a program that determines the largest of three given numbers.

num1 = 10
num2 = 14
num3 = 12

# uncomment following lines to take three numbers from user
#num1 = float(input("Enter first number: "))
#num2 = float(input("Enter second number: "))
#num3 = float(input("Enter third number: "))

if (num1 >= num2) and (num1 >= num3):
   largest = num1
elif (num2 >= num1) and (num2 >= num3):
   largest = num2
else:
   largest = num3

print("The largest number is", largest)

The largest number is 14


In [10]:
# 8. Develop a program that checks whether a character is a vowel or a consonant.

def vowelOrConsonant(x): 
  
    if (x == 'a' or x == 'e' or
        x == 'i' or x == 'o' or x == 'u'): 
        print("Vowel") 
    else: 
        print("Consonant") 
  

vowelOrConsonant('c') 
vowelOrConsonant('e')

Consonant
Vowel


In [11]:
# 9. Create a program to calculate the total cost of a shopping cart based on discounts.

def discountPercentage(S, M):
 
    # Calculating discount
    discount = M - S
 
    # Calculating discount percentage
    disPercent = (discount /M) * 100
 
    return disPercent
 
 

if __name__=='__main__':
    M = 120
    S = 100
 
    print(discountPercentage(S, M), "%")
 
    M = 1000
    S = 500
 
    print(discountPercentage(S, M), "%")

16.666666666666664 %
50.0 %


In [14]:
# 10. Write a program that checks if a given number is even or odd.

num = int (input ("Enter any number to test whether it is odd or even: "))

if (num % 2) == 0:

              print ("The number is even")

else:

              print ("The provided number is odd")


Enter any number to test whether it is odd or even:  6


The number is even


# Intermediate Level:

In [15]:
# 11. Write a program that calculates the roots of a quadratic equation .

import cmath

a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-3+0j) and (-2+0j)


In [17]:
# 12. Create a program that determines the day of the week based on the day number (1-7).

weekday = int(input("Enter weekday day number (1-7) : "))

if weekday == 1 :
    print("\nMonday");

elif weekday == 2 :
    print("\nTuesday")

elif(weekday == 3) :
    print("\nWednesday")

elif(weekday == 4) :
    print("\nThursday")

elif(weekday == 5) :
    print("\nFriday")

elif(weekday == 6) :
    print("\nSaturday")

elif (weekday == 7) :
    print("\nSunday")

else :
    print("\nPlease enter weekday number between 1-7.")

Enter weekday day number (1-7) :  5



Friday


In [18]:
# 13. Develop a program that calculates the factorial of a given number using recursion.

def recur_factorial(n):
   if n == 1:
       return n
   else:
       return n*recur_factorial(n-1)

num = 7

# check if the number is negative
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   print("The factorial of", num, "is", recur_factorial(num))

The factorial of 7 is 5040


In [19]:
# 14. Write a program to find the largest among three numbers without using the `max()` function.

num1 = 10
num2 = 14
num3 = 12

# uncomment following lines to take three numbers from user
#num1 = float(input("Enter first number: "))
#num2 = float(input("Enter second number: "))
#num3 = float(input("Enter third number: "))

if (num1 >= num2) and (num1 >= num3):
   largest = num1
elif (num2 >= num1) and (num2 >= num3):
   largest = num2
else:
   largest = num3

print("The largest number is", largest)

The largest number is 14


In [21]:
# 15. Create a program that simulates a basic ATM transaction menu.

user = {
    'pin': 1234,
    'balance':1000
}

def widthdraw_cash():
    while True:
        amount = int(input("Enter the amount of money you want to widthdraw: "))
        if amount > user['balance']:
            print("You don't have sufficient balance to make this widthdrawal")
        else:
            user['balance'] = user['balance'] - amount
            print(f"{amount} Dollars successfully widthdrawn your remaining balance is {user['balance']} Dollars")
            print('')
            return False

def balance_enquiry():
    print(f"Total balance {user['balance']} Dollars")
    print('')


is_quit = False

print('')
print("Welcome to the Pythondex ATM")

pin = int(input('Please enter your four digit pin: '))

if pin == user['pin']:
    while is_quit == False:
        print("what do you want to do")
        print(" Enter 1 to Widthdraw Cash \n Enter 2 for Balance Enquiry \n Enter 3 to Quit")

        query = int(input("Enter the number corresponding to the activity you want to do: "))

        if query == 1:
            widthdraw_cash()
        elif query == 2:
            balance_enquiry()
        elif query == 3:
            is_quit = True

        else:
            print("Please enter a correct value shown")
else:
    print("Entered wrong pin")


Welcome to the Pythondex ATM


Please enter your four digit pin:  1234


what do you want to do
 Enter 1 to Widthdraw Cash 
 Enter 2 for Balance Enquiry 
 Enter 3 to Quit


Enter the number corresponding to the activity you want to do:  2


Total balance 1000 Dollars

what do you want to do
 Enter 1 to Widthdraw Cash 
 Enter 2 for Balance Enquiry 
 Enter 3 to Quit


Enter the number corresponding to the activity you want to do:  3


In [23]:
# 16. Build a program that checks if a given string is a palindrome or not.

def isPalindrome(s):
    return s == s[::-1]

s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


In [24]:
# 17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values

def Average(lst): 
    return sum(lst) / len(lst) 
 
# Driver Code 
lst = [15, 9, 55, 41, 35, 20, 62, 49] 
average = Average(lst) 
 
# Printing average of the list 
print("Average of the list =", round(average, 2)) 

Average of the list = 35.75


In [25]:
# 18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

celsius = int(input("Enter the Temperature in Celsius :\n"))
fahrenheit = (1.8 * celsius) + 32
print("Temperature in Fahrenheit :", fahrenheit)

Enter the Temperature in Celsius :
 5


Temperature in Fahrenheit : 41.0


In [26]:
# 19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

def add(num1, num2):
    return num1 + num2
 
# Function to subtract two numbers
def subtract(num1, num2):
    return num1 - num2
 
# Function to multiply two numbers
def multiply(num1, num2):
    return num1 * num2
 
# Function to divide two numbers
def divide(num1, num2):
    return num1 / num2
 
print("Please select operation -\n" \
        "1. Add\n" \
        "2. Subtract\n" \
        "3. Multiply\n" \
        "4. Divide\n")
 
 
# Take input from the user
select = int(input("Select operations form 1, 2, 3, 4 :"))
 
number_1 = int(input("Enter first number: "))
number_2 = int(input("Enter second number: "))
 
if select == 1:
    print(number_1, "+", number_2, "=",
                    add(number_1, number_2))
 
elif select == 2:
    print(number_1, "-", number_2, "=",
                    subtract(number_1, number_2))
 
elif select == 3:
    print(number_1, "*", number_2, "=",
                    multiply(number_1, number_2))
 
elif select == 4:
    print(number_1, "/", number_2, "=",
                    divide(number_1, number_2))
else:
    print("Invalid input")

Please select operation -
1. Add
2. Subtract
3. Multiply
4. Divide



Select operations form 1, 2, 3, 4 : 1
Enter first number:  10
Enter second number:  20


10 + 20 = 30


In [28]:
# 20. Write a program that determines the roots of a cubic equation using the Cardano formula.

def verify(a,b,c,d,x):
    return (a*(x**3) + b*(x**2) + c*x + d)


roots = solve(a,b,c,d)

for x in roots:
    print(verify(a,b,c,d,x))

(1.1102230246251565e-16-4.593062973892975e-16j)
2.863727923517212e-16j
-1.2744788242756563e-16j


# Advanced Level:


In [36]:
# 21. Create a program that calculates the income tax based on the user's income and tax brackets.

while True:
    try:
        income = int(input("Please enter your taxable income in india: "))
    except ValueError:
        print("Sorry, We didn't understand that please enter taxable income as a number")
        continue
    else:
        break

if income <= 250000:  #2 Lakh 50 thousand
    tax = 0
elif income <= 500000: #5 Lakh
    tax = (income - 250000) * 0.05
elif income <= 750000: #7 lakh 50 thousand
    tax = (income - 500000) * 0.10 + 12500 
elif income <= 1000000: #10 Lakh
    tax = (income - 750000) * 0.15 + 37500 
elif income <= 1250000: #12 lakh 50 thousand
    tax = (income - 1000000) * 0.20 + 75000 
elif income <= 1500000: #15 lakh
    tax = (income - 1250000) * 0.25 + 125000 
else:
    tax = (income - 1500000) * 0.30 + 187500
print("you owe", tax, "Rupees in tax!")

Please enter your taxable income in india:  20000000


you owe 5737500.0 Rupees in tax!


In [37]:
# 22. Write a program that simulates a rock-paper-scissors game against the computer.

import random
user_choice=int(input("Enter your choice: type 0 for rock, type 1 for paper, type 2 for scissors."))
if user_choice >= 3 or user_choice <0:
    print("invalid number, you lose")
else:
    computer_choice=random.randint(0,2)
    print("computer chose")
    print(computer_choice)
    if computer_choice == user_choice :
        print("it's draw")
    elif computer_choice == 0 and user_choice == 2:
        print("you lose")
    elif user_choice == 0 and computer_choice == 2:
        print("you win")
    elif computer_choice > user_choice :
        print("you lose")
    elif user_choice > computer_choice :
        print("you win")

Enter your choice: type 0 for rock, type 1 for paper, type 2 for scissors. 0


computer chose
2
you win


In [43]:
# 23. Develop a program that generates a random password based on user preferences (length, complexity).

import string
import random
 
# Getting password length
length = int(input("Enter password length: "))
 
print('''Choose character set for password from these : 
         1. Digits
         2. Letters
         3. Special characters
         4. Exit''')
 
characterList = ""
 
# Getting character set for password
while(True):
    choice = int(input("Pick a number "))
    if(choice == 1):
         
        # Adding letters to possible characters
        characterList += string.ascii_letters
    elif(choice == 2):
         
        # Adding digits to possible characters
        characterList += string.digits
    elif(choice == 3):
         
        # Adding special characters to possible
        # characters
        characterList += string.punctuation
    elif(choice == 4):
        break
    else:
        print("Please pick a valid option!")
 
password = []
 
for i in range(length):
   
    # Picking a random character from our 
    # character list
    randomchar = random.choice(characterList)
     
    # appending a random character to password
    password.append(randomchar)
 
# printing password as a string
print("The random password is " + "".join(password))

Enter password length:  12345


Choose character set for password from these : 
         1. Digits
         2. Letters
         3. Special characters
         4. Exit


Pick a number  2
Pick a number  4


The random password is 07982728428219102974869419254207071377474826032162573528747405846568763536193386139885260994195108464895035856166800123428663436980612485717648614427708018501885241000754651030469054850211297972327864189433239126814236937353498398341734738123199099010550387658753573042981812369338505926779976366062964187619388611022105327150359302701026423220993505407811235349948071723513799388877059352128212586956284709619110821919248959342249937042107185773391401879440085739763732558891691053412556895732359442964610396986612731074570310322527976266930435331243479971202059170533106544623412390275527780486346994903907845726045968434994637265783961585201297259037405899205848999589057233890973725805204422175829081917469460930284342564732709645452475271166596662455201353498626614987889248235633738092786199009735602596122102684219039941838978832422106913779326984087513820689239349015628504002764076190369614836663037484065557197750653409174761555891375629241991905895394573777595759523

In [45]:
# 24. Create a program that implements a simple text-based adventure game with branching scenarios

answer_yes = ["Yes", "Y", "yes", "y"]
answer_no = ["No", "N", "no", "n"]

print("""
WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)
""")

ans1 = input(">>")

if ans1 in answer_yes:
    print("\nAfter 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)\n")

    ans2 = input(">>")

    if ans2 in answer_yes:
        print("\nYou are an honest person. He was a thief & You won the Game")

    elif ans2 in answer_no:
        print("\nYou helped a thief. Now, go to Jail. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

elif ans1 in answer_no:
    print("\nNow, he is trying to kill you. Will, you knock him down? (Yes / No)\n")

    ans3 = input(">>")

    if ans3 in answer_yes:
        print("\nCongrats! He was a thief & You helped the police to catch him with your bravery.")

    elif ans3 in answer_no:
        print("\nSorry! You are dead. He was a thief & He killed you. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

else:
    print("\nYou typed the wrong input. GOODBYE!")


WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)



>> Yes



After 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)



>> Yes



You are an honest person. He was a thief & You won the Game


In [46]:
# 25. Build a program that solves a linear equation for x, considering different cases.

from sympy import symbols, Eq, solve 
  
# defining symbols used in equations 
# or unknown variables 
x, y = symbols('x,y') 
  
# defining equations 
eq1 = Eq((x+y), 1) 
print("Equation 1:") 
print(eq1) 
eq2 = Eq((x-y), 1) 
print("Equation 2") 
print(eq2) 
  
# solving the equation 
print("Values of 2 unknown variable are as follows:") 
  
print(solve((eq1, eq2), (x, y)))

Equation 1:
Eq(x + y, 1)
Equation 2
Eq(x - y, 1)
Values of 2 unknown variable are as follows:
{x: 1, y: 0}


In [47]:
# 26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

print("Wellcome to quiz game !!")
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
score = 0
question_no = 0
playing = input('Do you want to play ? ').lower()
if playing == 'yes':
    question_no += 1
    ques = input(f'\n{question_no}. what does CPU stand for? ').lower()
    if ques == 'central processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> central processing unit')

# ------1
    question_no += 1
    ques = input(f'\n{question_no}. what does GPU stand for? ').lower()
    
    if ques == 'graphics processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> graphics processing unit')

# -----2
    question_no += 1
    ques = input(f'\n{question_no}. what does RAM stand for? ').lower()
    
    if ques == 'random access memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> random access memory')

# -----3
    question_no += 1
    ques = input(f'\n{question_no}. what does PSU stand for? ').lower()
    
    if ques == 'power supply unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> power supply unit')


# -----4
    question_no += 1
    ques = input(f'\n{question_no}. what does ROM stand for? ').lower()
    
    if ques == 'read only memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> read only memory')


# ------5 

else:
    print('thankyou you are out of a game.')
    quit()

print(f'\nnumber of question is {question_no}')
print(f'your score is {score}')
try:
    percentage = (score *100)/question_no
except ZeroDivisionError:
    print('0% quetions are correct')

print(f'{percentage}% questions are correct.')

Wellcome to quiz game !!
NOTE: if your spelling is incorrect then it is considered as wrong answer


Do you want to play ?  yes

1. what does CPU stand for?  sandka


Incorrect!
current answer is --> central processing unit



2. what does GPU stand for?  iashisa


Incorrect!
current answer is --> graphics processing unit



3. what does RAM stand for?  sas


Incorrect!
current answer is --> random access memory



4. what does PSU stand for?  csac


Incorrect!
current answer is --> power supply unit



5. what does ROM stand for?  sads


Incorrect!
current answer is --> read only memory

number of question is 5
your score is 0
0.0% questions are correct.


In [48]:
# 27. Develop a program that determines whether a given year is a prime number or not.

if num > 1:
    # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
        # If num is divisible by any number between
        # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

7 is a prime number


In [49]:
# 28. Create a program that sorts three numbers in ascending order using conditional statements.

num1=int(input("Enter First number : "))
num2=int(input("Enter Second number : "))
num3=int(input("Enter Third number : "))
if num1<num2 and num1<num3:
    if num2<num3:
        x,y,z=num1,num2,num3
    else:
        x,y,z=num1,num3,num2
elif num2<num1 and num2<num3:
    if num1<num3:
        x,y,z=num2,num1,num3
    else:
        x,y,z=num2,num3,num1
else:
    if num1<num2:
        x,y,z=num3,num1,num2
    else:
        x,y,z=num3,num2,num1
print("Numbers in ascending order are : ",x,y,z)

Enter First number :  5
Enter Second number :  9
Enter Third number :  17


Numbers in ascending order are :  5 9 17


In [50]:
# 29. Build a program that determines the roots of a quartic equation using numerical methods.

import math
 
# Prints roots of quadratic equation
# ax*2 + bx + x
def findRoots(a, b, c):
 
    # If a is 0, then equation is
    # not quadratic, but linear
    if a == 0:
        print("Invalid")
        return -1
    d = b * b - 4 * a * c
    sqrt_val = math.sqrt(abs(d))
 
    if d > 0:
        print("Roots are real and different ")
        print((-b + sqrt_val)/(2 * a))
        print((-b - sqrt_val)/(2 * a))
    elif d == 0:
        print("Roots are real and same")
        print(-b / (2*a))
    else:  # d<0
        print("Roots are complex")
        print(- b / (2*a), " + i", sqrt_val / (2 * a))
        print(- b / (2*a), " - i", sqrt_val / (2 * a))
 
 

if __name__ == '__main__':
    a = 1
    b = -7
    c = 12
     
    # Function call
    findRoots(a, b, c)

Roots are real and different 
4.0
3.0


In [51]:
# 30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based
#on the user's input.

weight = int(input());
height = float(input());
x = weight/float(height*height);
if x < 18.5:
    print('Underweight')
if x>=18.5 and x<25:
    print("Normal")
if x >= 25 and x < 30:
   print('Overweight')
if x >= 30:
   print('Obesity')

 60
 150


Underweight


# Challenge Level:

In [52]:
# 31. Create a program that validates a password based on complexity rules (length, characters, etc.).

def isValid(password):
 
    # for checking if password length
    # is between 8 and 15
    if (len(password) < 8 or len(password) > 15):
        return False
 
    # to check space
    if (" " in password):
        return False
 
    if (True):
        count = 0
 
        # check digits from 0 to 9
        arr = ['0', '1', '2', '3', 
        '4', '5', '6', '7', '8', '9']
 
        for i in password:
            if i in arr:
                count = 1
                break
 
        if count == 0:
            return False
 
    # for special characters
    if True:
        count = 0
 
        arr = ['@', '#','!','~','$','%','^',
                '&','*','(',',','-','+','/',
                ':','.',',','<','>','?','|']
 
        for i in password:
            if i in arr:
                count = 1
                break
        if count == 0:
            return False
 
    if True:
        count = 0
 
        # checking capital letters
        for i in range(65, 91):
 
            if chr(i) in password:
                count = 1
 
        if (count == 0):
            return False
 
    if (True):
        count = 0
 
        # checking small letters
        for i in range(97, 123):
 
            if chr(i) in password:
                count = 1
 
        if (count == 0):
            return False
 
    # if all conditions fails
    return True
 
# Driver code
password1 = "GeeksForGeeks"
 
if (isValid([i for i in password1])):
    print("Valid Password")
else:
    print("Invalid Password!!!")
 
password2 = "Geek$ForGeeks7"
if (isValid([i for i in password2])):
    print("Valid Password")
else:
    print("Invalid Password!!!")

Invalid Password!!!
Valid Password


In [53]:
# Develop a program that performs matrix addition and subtraction based on user input.

import numpy as np
 
 
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [54]:
# 33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
#algorithm.

def gcd(a, b):
    if a == 0:
        return b
 
    return gcd(b % a, a)
 
# Driver code
if __name__ == "__main__":
  a = 10
  b = 15
  print("gcd(", a, ",", b, ") = ", gcd(a, b))
 
  a = 35
  b = 10
  print("gcd(", a, ",", b, ") = ", gcd(a, b))
 
  a = 31
  b = 2
  print("gcd(", a, ",", b, ") = ", gcd(a, b))

gcd( 10 , 15 ) =  5
gcd( 35 , 10 ) =  5
gcd( 31 , 2 ) =  1


In [55]:
# 34. Build a program that performs matrix multiplication using nested loops and conditional statements.

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [59]:
# 35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.

import numpy as np
import random
from time import sleep
 
# Creates an empty board
 
 
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
 
# Check for empty places on board
 
 
def possibilities(board):
    l = []
 
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
 
# Select a random place for the player
 
 
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
 
# Checks whether the player has three
# of their marks in a horizontal row
 
 
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a vertical row
 
 
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a diagonal row
 
 
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
 
# Evaluates whether there is
# a winner or a tie
 
 
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
 
# Main function to start the game
 
 
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)

print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [1 0 0]
 [0 0 0]]
Board after 2 move
[[0 0 0]
 [1 0 0]
 [0 0 2]]
Board after 3 move
[[0 0 0]
 [1 0 0]
 [0 1 2]]
Board after 4 move
[[0 0 2]
 [1 0 0]
 [0 1 2]]
Board after 5 move
[[1 0 2]
 [1 0 0]
 [0 1 2]]
Board after 6 move
[[1 0 2]
 [1 2 0]
 [0 1 2]]
Board after 7 move
[[1 0 2]
 [1 2 0]
 [1 1 2]]
Winner is: 1


In [60]:
# 37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

def Fibonacci(n):
    if n<= 0:
        print("Incorrect input")
    # First Fibonacci number is 0
    elif n == 1:
        return 0
    # Second Fibonacci number is 1
    elif n == 2:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)
 
print(Fibonacci(10))

34


In [63]:
# 38. Create a program that generates a calendar for a given month and year using conditional statements.

# importing calendar module
import calendar

yy = 2023  # year
mm = 4    # month

# To take month and year input from the user
# yy = int(input("Enter year: "))
# mm = int(input("Enter month: "))

# display the calendar
print(calendar.month(yy, mm))

     April 2023
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



In [64]:
# 39. Build a program that simulates a basic text-based blackjack game against the computer.

import random 
  
card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades'] 
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'] 
deck = [(card, category) for category in card_categories for card in cards_list] 
  
def card_value(card): 
    if card[0] in ['Jack', 'Queen', 'King']: 
        return 10
    elif card[0] == 'Ace': 
        return 11
    else: 
        return int(card[0]) 
  
random.shuffle(deck) 
player_card = [deck.pop(), deck.pop()] 
dealer_card = [deck.pop(), deck.pop()] 
  
while True: 
    player_score = sum(card_value(card) for card in player_card) 
    dealer_score = sum(card_value(card) for card in dealer_card) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("\n") 
    choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower() 
    if choice == "play": 
        new_card = deck.pop() 
        player_card.append(new_card) 
    elif choice == "stop": 
        break
    else: 
        print("Invalid choice. Please try again.") 
        continue
  
    if player_score > 21: 
        print("Cards Dealer Has:", dealer_card) 
        print("Score Of The Dealer:", dealer_score) 
        print("Cards Player Has:", player_card) 
        print("Score Of The Player:", player_score) 
        print("Dealer wins (Player Loss Because Player Score is exceeding 21)") 
        break
  
while dealer_score < 17: 
    new_card = deck.pop() 
    dealer_card.append(new_card) 
    dealer_score += card_value(new_card) 
  
print("Cards Dealer Has:", dealer_card) 
print("Score Of The Dealer:", dealer_score) 
print("\n") 
  
if dealer_score > 21: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)") 
elif player_score > dealer_score: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Player wins (Player Has High Score than Dealer)") 
elif dealer_score > player_score: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Dealer wins (Dealer Has High Score than Player)") 
else: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("It's a tie.")

Cards Player Has: [('9', 'Hearts'), ('Jack', 'Spades')]
Score Of The Player: 19




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('9', 'Hearts'), ('Jack', 'Spades'), ('7', 'Hearts')]
Score Of The Player: 26




What do you want? ["play" to request another card, "stop" to stop]:  stop


Cards Dealer Has: [('9', 'Clubs'), ('3', 'Hearts'), ('Ace', 'Clubs')]
Score Of The Dealer: 23


Cards Dealer Has: [('9', 'Clubs'), ('3', 'Hearts'), ('Ace', 'Clubs')]
Score Of The Dealer: 23
Cards Player Has: [('9', 'Hearts'), ('Jack', 'Spades'), ('7', 'Hearts')]
Score Of The Player: 26
Player wins (Dealer Loss Because Dealer Score is exceeding 21)


In [65]:
# 40. Write a program that generates the prime factors of a given number using trial division.

def TrialDivision(N):
 
    # Initializing with the value 2 
    # from where the number is checked
    i = 2
 
    # Computing the square root of 
    # the number N
    k = int(N ** 0.5)
 
    # While loop till the 
    # square root of N
    while(i<= k):
 
        # If any of the numbers between 
        # [2, sqrt(N)] is a factor of N 
        # Then the number is composite
        if(N % i == 0):
            return 0
        i += 1
 
    # If none of the numbers is a factor,
    # then it is a prime number
    return 1
     
# Driver code
if __name__ == "__main__":
    N = 49
    p = TrialDivision(N)
 
# To check if a number is a prime or not
    if(p):
        print("Prime")
    else:
        print("Composite")

Composite
